/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 shirt_baked.glb 
*/

import React from "react";
import { Decal, useGLTF, useTexture } from "@react-three/drei";
import { useSnapshot } from "valtio";
import state from "../src/store";
import { useFrame } from "@react-three/fiber";
import { easing } from "maath";

export default function Model(props) {
  const snap = useSnapshot(state);
  const logoTexture = useTexture(snap.logoDecal);
  const fullTexture = useTexture(snap.fullDecal);
  const { nodes, materials } = useGLTF("/shirt_baked.glb");

  useFrame((state, delta) => {
    easing.dampC(materials.lambert1.color,snap.color, 0.25, delta);
  })

  const stateString = JSON.stringify(snap);

  return (
    <group key={stateString} {...props} dispose={null}>
      <mesh
        geometry={nodes.T_Shirt_male.geometry}
        material={materials.lambert1}
      >
        {snap.isFullTexture && (
          <Decal
            position={[0, 0, 0]}
            rotation={[0, 0, 0]}
            scale={1}
            map={fullTexture}
          />
        )}

        {snap.isLogoTexture && (
          <Decal
            position={[0, 0.04, 0.15]}
            rotation={[0, 0, 0]}
            scale={0.15}
            map={logoTexture}
            map-anisotropy={16}
            depthTest={false}
            depthWrite={true}

          />
        )}
      </mesh>
    </group>
  );
}

useGLTF.preload("/shirt_baked.glb");
